# Generated by Django 6.0.3 on 2026-04-11 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("numero", models.IntegerField()),
                ("ano", models.IntegerField()),
                ("formacao_texto", models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name="Licenciatura",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("duracao", models.IntegerField()),
                ("creditos", models.IntegerField()),
                ("informacao", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="MakingOF",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("justificacao", models.CharField(max_length=250)),
                ("solucao", models.CharField(max_length=150)),
                ("uso_ia", models.BooleanField()),
                ("descricao_uso_ia", models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("disciplina", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("data_de_realizacao", models.DateField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=150)),
                ("descricao", models.CharField(max_length=200)),
                ("site", models.URLField()),
                (
                    "interesse",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                ("instituicao", models.CharField(max_length=150)),
                ("data_inicio", models.DateField()),
                ("data_conclusao", models.DateField()),
                ("descricao", models.CharField(max_length=200)),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.aluno",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aluno",
            name="licenciatura",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="portfolio.licenciatura"
            ),
        ),
        migrations.CreateModel(
            name="Competencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=100)),
                (
                    "nivel",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "experiencia",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ]
                    ),
                ),
                ("projetos", models.ManyToManyField(to="portfolio.projeto")),
            ],
        ),
        migrations.AddField(
            model_name="projeto",
            name="tecnologias",
            field=models.ManyToManyField(to="portfolio.tecnologia"),
        ),
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("ano", models.IntegerField()),
                ("tema", models.CharField(max_length=100)),
                (
                    "autor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.aluno",
                    ),
                ),
                (
                    "orientador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.professor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnidadeCurricular",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=200)),
                ("creditos", models.IntegerField()),
                ("imagem", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "professor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.professor",
                    ),
                ),
                ("projetos", models.ManyToManyField(to="portfolio.projeto")),
            ],
        ),
    ]
