# Generated by Django 6.0.3 on 2026-04-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="professor",
            name="disciplina",
        ),
        migrations.RemoveField(
            model_name="unidadecurricular",
            name="professor",
        ),
        migrations.AddField(
            model_name="professor",
            name="unidades_curriculares",
            field=models.ManyToManyField(blank=True, to="portfolio.unidadecurricular"),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="professores",
            field=models.ManyToManyField(blank=True, to="portfolio.professor"),
        ),
        migrations.AlterField(
            model_name="aluno",
            name="numero",
            field=models.DecimalField(decimal_places=0, max_digits=8),
        ),
    ]
