# Generated by Django 6.0.3 on 2026-04-11 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_remove_professor_disciplina_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unidadecurricular",
            name="professores",
            field=models.ManyToManyField(to="portfolio.professor"),
        ),
    ]
